### ISSUE TITLE
Incorrect originPort in configuration after site creation

### ISSUE THREAD

**Issue by dermyrddin** [danielstutzman/terraform-provider-belugacdn#1]
First of all thanks for your work )

The issue maybe related to go-belugacdn project. After site creation beluga cli prints that 
"originPort" is set to 0, but web configuration shows 80. So created site is not working until this setting is not updated or removed.

**Comment by danstutzman** [comment]
Hmm I'm not sure setting originPort to 0 explains why your created site is not working.  In my experience it takes maybe an hour or two for BelugaCDN to set up new sites; have you waited that long?  In any case, I've set the default for `origin_port` to 80 in c541b7b48d5144ebe822fbe9c097dd7f9589d5d0 to eliminate this uncertainty in the future.

**Comment by dermyrddin** [comment]
Yes, deploying delay is very unpleasant (in my case it was about 30 minutes). But it's not the case of problem. After deploy completes Beluga site responses with 503 error as it couldn't connect to the origin via port 0. After resave settings via web ui problem resolves.

When creating site via web ui parameter originPort is absent in configuration before you make any change in the ui. You can check it with "beluga --path sites" command.

**Comment by danstutzman** [comment]
Understood.  Please retest with c541b7b48d5144ebe822fbe9c097dd7f9589d5d0 and confirm that it's now fixed.

**Comment by dermyrddin** [comment]
Yes, it's fixed now. Thanks.
